### ISSUE TITLE
"float" bug

### ISSUE THREAD

**Issue by unique-zz** [docyes/cssugar#1]
There is an issue with "float" CSS property. CSSugar does not apply it, I think because "float" is a keyword in Javascript.

**Comment by unique-zz** [comment]
The possible workaround is to use "cssFloat" property insteed

**Comment by docyes** [comment]
I can replicate this issue on FF. Strange because float is not a reserved word. Will look into this more.

**Comment by docyes** [comment]
Looks like the attribute reference in JavaScript is cssFloat - http://www.w3schools.com/css/pr_class_float.asp I guess you learn something new everyday.

**Comment by docyes** [comment]
Fix added: http://github.com/docyes/cssugar/commit/866cbf87703e201cd889145c85fc02e3013c89c9

**Comment by unique-zz** [comment]
Cool thanx, idea with general purpose remapper object sounds good.
